set search_path to nmc;

CREATE TABLE results(
	TestCaseID	 int REFERENCES testcase(testcaseid),
	build	varchar(25),
	result	varchar(4),
	remarks varchar(200)
);

CREATE TABLE userroleactionrights(
	TestCaseID	 int REFERENCES testcase(testcaseid),
	reopen_bill char(1),
	direct_billing char(1),
	add_items_to_bill char(1),
	create_bill_for_closed_visit char(1),
	cancel_bill char(1),
	cancel_items_in_bill char(1),
	allow_refunds char(1),
	allow_discounts char(1),
	allow_all_rate_increase char(1),
	allow_all_rate_decrease char(1),
	view_all_rates_in_order char(1),
	view_general_rates_in_order char(1),
	allow_back_date char(1),
	allow_receipt_back_date char(1),
	allocate_shift_bed char(1),
	allow_set_charges_bed_type char(1),
	edit_inactive_visit_discharge_summary char(1),
	edit_reg_first_name char(1),
	edit_reg_custom_fields char(1),
	patient_category_change char(1),
	signoff_labser_reports char(1),
	allow_new_reg char(1),
	cancel_test char(1),
	allow_retail_credit_sales char(1),
	allow_max_cost_price_change char(1),
	show_avble_qty_on_raiseindent char(1),
	reopen_codification char(1),
	allow_direct_stock_entry char(1),
	user_counter_day_book char(1),
	edit_receipt_amount char(1),
	cancel_app char(1),
	new_bill_for_order char(1),
	validate_test_result char(1),
	revert_signoff char(1),
	amend_test_result char(1),
	amend_score_card_values char(1),
	reopen_cons_after_time_limit char(1),
	return_ph_item_after_validity char(1),
	package_approval char(1),
	pbm_prescription_finalize char(1),
	erx_consultation_access char(1),
	erx_dis_medication char(1),
	allow_prior_auth_presc_edit char(1),
	reg_charge_appl char(1),
	patient_header_edit char(1),
	allow_back_date_app char(1),
	del_pat_gen_doc char(1),
	allow_denial_accept char(1),
	val_discharge_summary_report char(1),
	del_discharge_summary_report char(1),
	reopen_discharge_summary_report char(1),
	signoff_blood_trans char(1),
	allow_view_off_clinical_alerts char(1),
	birth_reg char(1)
);


CREATE TABLE userrolescreenrights(
	TestCaseID	 int REFERENCES testcase(testcaseid),
	RoleName varchar(25) NOT NULL,
	PatientSearch char(1),
	Registration char(1),
	Billing char(1),
	DischargeSummary char(1),
	CancerActivities char(1),
	Payments char(1),
	Services char(1),
	OTServices char(1),
	OTManagement char(1),
	Laboratory char(1),
	Radiology char(1),
	Scheduler char(1),
	InPatient char(1),
	Dialysis char(1),
	ClinicalData char(1),
	DoctorConsultation char(1),
	OutPatient char(1),
	MedicalRecords char(1),
	SalesIssues char(1),
	Procurement char(1),
	StoreMgmt char(1),
	Insurance char(1),
	ERxAuthorization char(1),
	MaintContracts char(1),
	PatientStatsReports char(1),
	PatientFeedbackReports char(1),
	RosterReports char(1),
	CSSD char(1),
	AdvancedPackages char(1),
	MaintContractsReports char(1),
	FinancialReports char(1),
	BillingReports char(1),
	SalesIssuesReports char(1),
	ProcurementReports char(1),
	StoreMgmtReports char(1),
	DiagnosticsReports char(1),
	PatientPackageReports char(1),
	DialysisReports char(1),
	ClinicalDataReports char(1),
	ServiceReports char(1),
	ConsultationReports char(1),
	SchedulerReports char(1),
	OTReports char(1),
	BedUtilReports char(1),
	DentalReports char(1),
	WardActivitiesReports char(1),
	InsuranceReports char(1),
	DietaryReports char(1),
	MRDReports char(1),
	MasterReports char(1),
	CustomReports char(1),
	FavouriteReports char(1),
	Preferences char(1),
	BillingPreferences char(1),
	PrintTemplates char(1),
	DocumentTemplates char(1),
	GeneralMasters char(1),
	HospitalAdminMasters char(1),
	HospitalBillingMasters char(1),
	DentalMasters char(1),
	Roster char(1),
	StoresMasters char(1),
	MessagingMasters char(1),
	Administration char(1),
	Dietary char(1),
	PatientFeedback char(1),
	Common char(1)
);

CREATE TABLE logindata(
   TestCaseID	 int REFERENCES testcase(testcaseid),
   Hospital      varchar(10)      NOT NULL,
   UserName	 varchar(40)      NOT NULL,
   Password      varchar(15)	NOT NULL,
   AltPassword	 varchar(15)
);

ALTER TABLE testcase
ADD CONSTRAINT uniquekey UNIQUE (Module,ActionClass,Description);

CREATE TABLE testcase(
   TestCaseID  SERIAL PRIMARY KEY,
   Module      varchar(40)      NOT NULL,
   ActionClass varchar(40)      NOT NULL,
   Author      varchar(15)	NOT NULL,
   Description varchar(2000)    NOT NULL
);